package InterfazGUI;


import Excepciones.ExceptionDNI;
import Vivero.Vivero;

import javax.swing.*;
import java.io.IOException;
import java.util.Objects;

/**
 *
 * @author Gian
 */
public class VentanaEditarCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEditarCliente
     */
    private Vivero vivero;
    private int dni;
    public VentanaEditarCliente(int DNI, Vivero vivero) {
        initComponents();
        setTitle("Editar cliente");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        GUI.setupButton(Volver);
        GUI.setupButton(Guardar);
        setResizable(false);
        this.dni=DNI;
        this.vivero=vivero;
        System.out.println(vivero.listar());
        cargar();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Volver = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        CategoriaCmBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/Imagenes/marchitez-de-la-planta-solar.png"))).getImage());
        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setForeground(new java.awt.Color(0, 0, 0));

        Volver.setBackground(new java.awt.Color(52, 102, 255));
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("Volver");
        Volver.setBorder(null);
        Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre");

        Apellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Apellido.setForeground(new java.awt.Color(0, 0, 0));
        Apellido.setText("Apellido");


        Categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Categoria.setForeground(new java.awt.Color(0, 0, 0));
        Categoria.setText("Categoria");

        Guardar.setBackground(new java.awt.Color(52, 102, 255));
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.setBorder(null);
        Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        CategoriaCmBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monotributista", "Responsable Inscripto", "Consumidor final" }));
        CategoriaCmBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //CategoriaCmBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Apellido)
                                        .addComponent(Nombre))
                                .addGap(35, 35, 35)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(78, 78, 78)
                                                .addComponent(Categoria)
                                                .addGap(28, 28, 28)
                                                .addComponent(CategoriaCmBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(156, 156, 156))
        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Nombre)
                                        .addComponent(CategoriaCmBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Categoria))
                                .addGap(43, 43, 43)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Apellido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {
        Cliente cliente=new Cliente();
        cliente.setVisible(true);// TODO add your handling code here:
        setVisible(false);
    }

    private void cargar()
    {
        Clientes.Cliente aux=(Clientes.Cliente) vivero.buscar(dni);
        txtNombre.setText(aux.getNombre());
        txtApellido.setText(aux.getApellido());
        CategoriaCmBox.setSelectedItem(aux.getCategoria());
    }


    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Clientes.Cliente cliente = new Clientes.Cliente();
            cliente.setNombre(txtNombre.getText());
            cliente.setApellido(txtApellido.getText());
            cliente.setDni(dni);
            cliente.setCategoria((String) CategoriaCmBox.getSelectedItem());


            if(  txtNombre.getText().equals("") ||  txtApellido.getText().equals("") )
            {
                throw new NumberFormatException("Campos vacios");
            }

            try {
                vivero.getClientes().put(dni,cliente);
                vivero.guardarEnArchivo("archivo.json");
                JOptionPane.showMessageDialog(null, "Usuario registrado exitosamente");
            }catch (IOException e)
            {
                System.out.println(e.getMessage());
            }
            catch (Exception e)
            {
                JOptionPane.showInternalMessageDialog(null, "Ya existe un cliente con ese DNI", "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println(e.getMessage());
            }
            txtNombre.setText("");
            txtApellido.setText("");
            CategoriaCmBox.setSelectedItem("Consumidor Final");


            System.out.println(vivero.listar());
        }
        catch (NumberFormatException e)
        {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Debe rellenar los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }



    /**
     */



    // Variables declaration - do not modify
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Categoria;
    private javax.swing.JComboBox<String> CategoriaCmBox;
    private javax.swing.JButton Guardar;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration
}
